<?php

//English

//common

define("_BACK","Back");
define("_MAIL","Mail");
define("_PASSWORD","Password");
define("_CONNECTION","Connection");

//header unSession

define("_WELCOME","Welcome to the BIG-MAP website !");

//header session

define("_MYPROFIL","My profil");

//footer

define("_COPYRIGHT","©Team BIGMAP <br> Proposed by Infinite Measure and developed by the company BIGMAP® / APP / Copyright ©2020");

//lefter

define("_HOME","Home");
define("_DASHBOARD","Dashboard");
define("_CALENDAR","Calendar");

define("_TESTRESULT","Test results");
define("_SCORE","Score");

define("_USERLIST","User list");
define("_PERFORMTEST","Perform a test");

define("_MODIFYRESULT","Modify result");
define("_MANAGEACCESSRIGHT","Manage access right");

define("_FAQ","FAQ");
define("_TICKETS","Tickets");
define("_LOGOUT","Logout");

//connection

define("_NOACCOUNT","No account ?");

//home

define("_TESTRESULTS","Your test results");

//contact us

define("_CONTACTUS","Contact us");
define("_MESSAGE","Message");

//forgot password

define("_FORGOTPASSWORD","Forgot password ?");
define("_MAILPASSWORD","Please enter your email:");
define("_NEWPASSWORD","Reset password");
define("_MESSAGESENT","Your message has been sent");
define("_MESSAGENOTSENT","Your message could not be sent");
define("_MESSAGECONTENT", "This is your new password: ");

//inscription

define("_INSCRIPTION","Inscription");
define("_FIRSTNAME","First name");
define("_LASTNAME","Last name");
define("_REGISTERON","Register on");
define("_USER","User");
define("_ORGANISM","Organism");
define("_ADMIN","Admin");
define("_PASSWORDCONFIRMATION","Password confirmation");
define("_ACCEPTGTU","Accept GTU");
define("_SUBMIT","Submit");
define("_SEX","Sex");
define("_MAN","Man");
define("_WOMEN","Women");
define("_OTHER","Other");
define("_BIRTHDATE","Birthdate");
define("_COMMENT","Comment");
define("_PRACTICESPORT","What sport(s) do you practice ?");
define("_JOBS","What job(s) do you do ?");
define("_HANDICAPS","What handicap(s) do you have ?");

define("_ORGANISMNAME","Organism name");
define("_ORGANISMMAIL","Organism mail");
define("_ADDRESS","Address");
define("_COUNTRY","Country");
define("_CITY","City");
define("_POSTALCODE","Postal code");
define("_PHONE","Phone number");
define("_ORGANISMTYPE","Organism type");
define("_DRIVINGSCHOOL","Driving school");
define("_ARMY","Army");
define("_NGO","NGO");


//404

define("_404","Error 404");

//presentation

define("_WHOAREWE","Who are we ?");
define("_PRESENTATION","Presentation");
define("_PRESENTATIONTEXT","Presentation about Infinite Measures");

//GTU

define("_GTU","GTU");

//access deny

define("_ACCESSDENY","Acces deny !");

//FAQ

define("_MODIFY","Modify");
define("_DELETE","Delete");
define("_ADDMODIFY","Add or modify FAQ");
define("_QUESTION","Question");
define("_ANSWER","Answer");
define("_LANGUAGE","Language");
define("_DELETEMESSAGE", "The question has been deleted");
define("_NOTDELETEMESSAGE", "The question has not been deleted");

//user list

define("_NOMEMBER","No member");
