<?php

//English

//common

define("_BACK","Back");
define("_MAIL","Mail");
define("_PASSWORD","Password");
define("_CONNECTION","Connection");

//header logout

define("_WELCOME","Welcome to the BIG-MAP website !");

//header login

define("_MYPROFIL","My profil");

//footer

define("_COPYRIGHT","©TEAM BIGMAP <br> Proposed by Infinite Measure and developed by the company BIGMAP® / APP / Copyright ©2020");

//main-nav

define("_HOME","Home");
define("_DASHBOARD","Dashboard");
define("_CALENDAR","Calendar");

define("_TESTRESULT","Test results");
define("_SCORE","Score");

define("_USERLIST","User list");
define("_PERFORMTEST","Perform a test");

define("_MODIFYRESULT","Modify result");
define("_MANAGEACCESSRIGHT","Manage access right");

define("_FAQ","FAQ");
define("_TICKETS","Tickets");
define("_LOGOUT","Logout");

//connection

define("_NOACCOUNT","No account ?");

//contact us

define("_CONTACTUS","Contact us");
define("_MESSAGE","Message");

//forgot password

define("_FORGOTPASSWORD","Forgot password ?");

//inscription

define("_INSCRIPTION","Inscription");
define("_FIRSTNAME","First name");
define("_LASTNAME","Last name");
define("_REGISTERON","Register on");
define("_USER","User");
define("_ORGANISM","Organism");
define("_ADMIN","Admin");
define("_PASSWORDCONFIRMATION","Password confirmation");
define("_ACCEPTGTU","Accept GTU");
define("_SUBMIT","Submit");
define("_SEX","Sex");
define("_MAN","Man");
define("_WOMEN","Women");
define("_OTHER","Other");
define("_BIRTHDATE","Birthdate");
define("_COMMENT","Comment");
define("_PRACTICESPORT","What sport(s) do you practice ?");
define("_JOBS","What job(s) do you do ?");
define("_HANDICAPS","What handicap(s) do you have ?");

define("_ORGANISMNAME","Organism name");
define("_ORGANISMMAIL","Organism mail");
define("_ADDRESS","Address");
define("_COUNTRY","Country");
define("_CITY","City");
define("_POSTALCODE","Postal code");
define("_PHONE","Phone number");
define("_ORGANISMTYPE","Organism type");
define("_DRIVINGSCHOOL","Driving school");
define("_ARMY","Army");
define("_NGO","NGO");


//404

define("_404","Error 404");

//presentation

define("_WHOAREWE","Who are we ?");
define("_PRESENTATION","Presentation");
define("_PRESENTATIONTEXT","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sollicitudin tellus quis volutpat rutrum. Praesent mauris massa, dignissim et mollis quis, feugiat at mi. Maecenas velit lorem, tincidunt iaculis auctor maximus, sodales in eros. Pellentesque lacinia laoreet tellus sed vehicula. In in urna nec nunc feugiat feugiat vel et nibh. Fusce accumsan enim ut ultricies euismod. Pellentesque gravida magna libero, eget vestibulum enim porta in. Proin ac quam eu tortor pretium porta. Phasellus dignissim est sit amet dapibus dapibus. Morbi ut dui eget ipsum viverra maximus. Sed quis nulla rhoncus dolor tincidunt maximus id eget est. Fusce ut nisl congue nunc ultrices porttitor. Sed semper enim et felis viverra ultricies. Phasellus dictum, augue vel dignissim iaculis, mi felis tempus sapien, ac efficitur orci sem iaculis ante.
<br>
<br>
Suspendisse vitae ante venenatis, tristique libero tempor, elementum mi. Vestibulum id erat dictum, mollis risus quis, accumsan turpis. Donec a faucibus tellus, sed tempus ligula. Aliquam commodo tortor in elit sodales tristique. Praesent pretium sapien ullamcorper, accumsan enim nec, porttitor magna. Sed finibus libero purus, molestie gravida nisi viverra eget. Vivamus elementum mauris at ligula auctor, sed feugiat erat volutpat. Curabitur volutpat, augue at volutpat ultricies, massa ligula aliquet urna, et dignissim elit nunc viverra purus. Mauris laoreet urna eros, non vulputate massa tempus condimentum. Nullam faucibus ex est, at aliquet sem mollis non. Vivamus et aliquet lacus.
<br>
<br>
Mauris nec mollis nulla, ornare finibus quam. Curabitur hendrerit turpis sem, eget convallis lectus pharetra lobortis. Nam venenatis magna iaculis sapien feugiat, laoreet luctus elit porta. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras finibus tortor lorem, ultricies egestas ante vulputate non. Phasellus in purus lacinia, blandit lectus egestas, luctus mi. Donec eget urna metus. Nam sollicitudin leo ligula, non placerat orci dapibus non. Ut commodo consectetur luctus.
<br>
<br>
Etiam suscipit at nibh sit amet luctus. Ut semper sed libero mollis maximus. Ut finibus efficitur nulla, sed ultricies augue sagittis accumsan. Donec molestie et risus at rutrum. Nulla id tempus est. Vivamus eleifend nulla a elit volutpat finibus. Aenean convallis aliquet mi quis suscipit. Suspendisse a feugiat nulla. Vestibulum suscipit volutpat gravida. Aliquam congue sit amet mi commodo fermentum. Cras rutrum id est at viverra. Nam elementum enim vel nunc sagittis laoreet. Aliquam eleifend metus et massa dictum rutrum. Donec quis finibus purus, non mollis erat. Sed tincidunt urna a laoreet fermentum.
<br>
<br>
Praesent vestibulum, nulla eget rutrum pretium, nibh augue imperdiet justo, id semper metus tellus at mi. In pharetra lacinia ligula, vitae feugiat nisi egestas a. Aliquam lorem dui, ullamcorper non vestibulum non, dictum quis neque. Morbi vitae urna purus. In ac erat ultrices, varius lacus vel, viverra nunc. Etiam vel felis ultrices, hendrerit ante quis, consequat mi. Nullam in tellus ligula. Nam ut sollicitudin risus. Pellentesque a commodo est, lacinia maximus turpis. Aenean congue in lorem quis congue. In hac habitasse platea dictumst. Aliquam quam turpis, dignissim ac quam vulputate, scelerisque luctus urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque a molestie dolor. Sed vel nulla metus.");

//GTU

define("_GTU","GTU");

//access deny

define("_ACCESSDENY","Acces deny !");

//FAQ

define("_MODIFY","Modify");
define("_DELETE","Delete");
define("_ADDQUESTION","Add a question/answer :");
define("_QUESTION","Question");
define("_ANSWER","Answer");
define("_LANGUAGE","Language");

//user list

define("_NOMEMBER","No member");

//Score

define("_SCORECOMMENTUSER","My average score compared to the general average:");
define("_SCORECOMMENTORGANISM","Average score of my organization compared to other organizations:");

define("_HEARTBEAT","Heartbeat");
define("_VISUALREFLEX","Visual reflex");
define("_HEARINGTEST","Hearing test");
define("_SOUNDREFLEX","Sound reflex");
define("_AVERAGE","Average");
