<?php

//Français

//common

define("_BACK","Retour");
define("_MAIL","Mail");
define("_PASSWORD","Mot de passe");
define("_CONNECTION","Connection");

//header unSession

define("_WELCOME","Bienvenue sur le site BIG-MAP !");

//header session

define("_LOGOUT","Déconnexion");

//footer

define("_COPYRIGHT","Copyright, site réalisé par BIG-MAP, mentions légales, 2020.");

//lefter

define("_DASHBOARD","Tableau de bord");
define("_CALENDAR","Calendrier");

//connection

define("_NOACCOUNT","Pas de compte ?");

//contact us

define("_CONTACTUS","Contactez-nous");

//forgot password

define("_FORGOTPASSWORD","Mot de passe oublié ?");
define("_MAILPASSWORD","Veuillez renseigner votre mail:");
define("_NEWPASSWORD","Réinitialiser le mot de passe");
define("_MESSAGESENT","Votre message a bien été envoyé");
define("_MESSAGENOTSENT","Votre message n'a pas pu être envoyé");

//inscription

define("_INSCRIPTION","Inscription");
define("_FIRSTNAME","Prénom");
define("_LASTNAME","Nom");
define("_REGISTERON","S'enregistrer en tant qu'");
define("_USER","Utilisateur");
define("_ORGANISM","Organisme");
define("_ADMIN","Administrateur");
define("_PASSWORDCONFIRMATION","Confirmation mot de passe");
define("_ACCEPTGTU","Accepter les CGU");
define("_SUBMIT","Ajouter");
define("_SEX","Sexe");
define("_MAN","Homme");
define("_WOMEN","Femme");
define("_OTHER","Autre");
define("_BIRTHDATE","Date de naissance");
define("_COMMENT","Commentaire");
define("_PRACTICESPORT","Quel(s) sport(s) pratiquer vous ?");
define("_JOBS","Quel(s) métier faites-vous ?");
define("_HANDICAPS","Quel(s) handicap(s) avez vous ?");

//404

define("_404","Erreur 404");

//presentation

define("_WHOAREWE","Qui sommes-nous ?");
define("_PRESENTATION","Présentation");

//GTU

define("_GTU","CGU");

//ACCESS DENY

define("_ACCESSDENY","Accès non autorisé !");