<?php

//Français

//common

define("_BACK","Retour");
define("_MAIL","Mail");
define("_PASSWORD","Mot de passe");
define("_CONNECTION","Connection");

//header logout

define("_WELCOME","Bienvenue sur le site BIG-MAP !");

//header login

define("_MYPROFIL","Mon profil");

//footer

define("_LEGALNOTICE","Copyright, site réalisé par BIG-MAP, mentions légales, 2020.");
define("_COPYRIGHT","©TEAM BIGMAP <br> Proposé par Infinite Measures et dévéloppé par la société BigMap®/ APP / Copyright ©2020");

//main-nav

define("_HOME","Accueil");
define("_DASHBOARD","Tableau de bord");
define("_CALENDAR","Calendrier");

define("_TESTRESULT","Résultats des tests");
define("_SCORE","Scores");

define("_USERLIST","Liste d'utilisateurs");
define("_PERFORMTEST","Effectuer un test");

define("_MODIFYRESULT","Modifier les résultats");
define("_MANAGEACCESSRIGHT","Gérer les droits d'accès");

define("_FAQ","FAQ");
define("_TICKETS","Envoyer un ticket");
define("_LOGOUT","Déconnexion");


//connection

define("_NOACCOUNT","Pas de compte ?");

//contact us

define("_CONTACTUS","Nous contacter");
define("_MESSAGE","Message");

//forgot password

define("_FORGOTPASSWORD","Mot de passe oublié ?");

//inscription

define("_INSCRIPTION","Inscription");
define("_FIRSTNAME","Prénom");
define("_LASTNAME","Nom");
define("_REGISTERON","S'enregistrer en tant que ");
define("_USER","Utilisateur");
define("_ORGANISM","Organisme");
define("_ADMIN","Administrateur");
define("_PASSWORDCONFIRMATION","Confirmation mot de passe");
define("_ACCEPTGTU","Accepter les CGU");
define("_SUBMIT","Ajouter");
define("_SEX","Sexe");
define("_MAN","Homme");
define("_WOMEN","Femme");
define("_OTHER","Autre");
define("_BIRTHDATE","Date de naissance");
define("_COMMENT","Commentaire");
define("_PRACTICESPORT","Quel(s) sport(s) pratiquer vous ?");
define("_JOBS","Quel(s) métier faites-vous ?");
define("_HANDICAPS","Quel(s) handicap(s) avez vous ?");

define("_ORGANISMNAME","Nom de l'organisme");
define("_ORGANISMMAIL","Mail de l'organisme");
define("_ADDRESS","Addresse");
define("_COUNTRY","Pays");
define("_CITY","Ville");
define("_POSTALCODE","Code Postal");
define("_PHONE","Téléphone");
define("_ORGANISMTYPE","Type d'organisme");
define("_DRIVINGSCHOOL","Auto-école");
define("_ARMY","Armée");
define("_NGO","ONG");
//404

define("_404","Erreur 404");

//presentation

define("_WHOAREWE","Qui sommes-nous ?");
define("_PRESENTATION","Présentation");
define("_PRESENTATIONTEXT","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sollicitudin tellus quis volutpat rutrum. Praesent mauris massa, dignissim et mollis quis, feugiat at mi. Maecenas velit lorem, tincidunt iaculis auctor maximus, sodales in eros. Pellentesque lacinia laoreet tellus sed vehicula. In in urna nec nunc feugiat feugiat vel et nibh. Fusce accumsan enim ut ultricies euismod. Pellentesque gravida magna libero, eget vestibulum enim porta in. Proin ac quam eu tortor pretium porta. Phasellus dignissim est sit amet dapibus dapibus. Morbi ut dui eget ipsum viverra maximus. Sed quis nulla rhoncus dolor tincidunt maximus id eget est. Fusce ut nisl congue nunc ultrices porttitor. Sed semper enim et felis viverra ultricies. Phasellus dictum, augue vel dignissim iaculis, mi felis tempus sapien, ac efficitur orci sem iaculis ante.
<br>
<br>
Suspendisse vitae ante venenatis, tristique libero tempor, elementum mi. Vestibulum id erat dictum, mollis risus quis, accumsan turpis. Donec a faucibus tellus, sed tempus ligula. Aliquam commodo tortor in elit sodales tristique. Praesent pretium sapien ullamcorper, accumsan enim nec, porttitor magna. Sed finibus libero purus, molestie gravida nisi viverra eget. Vivamus elementum mauris at ligula auctor, sed feugiat erat volutpat. Curabitur volutpat, augue at volutpat ultricies, massa ligula aliquet urna, et dignissim elit nunc viverra purus. Mauris laoreet urna eros, non vulputate massa tempus condimentum. Nullam faucibus ex est, at aliquet sem mollis non. Vivamus et aliquet lacus.
<br>
<br>
Mauris nec mollis nulla, ornare finibus quam. Curabitur hendrerit turpis sem, eget convallis lectus pharetra lobortis. Nam venenatis magna iaculis sapien feugiat, laoreet luctus elit porta. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras finibus tortor lorem, ultricies egestas ante vulputate non. Phasellus in purus lacinia, blandit lectus egestas, luctus mi. Donec eget urna metus. Nam sollicitudin leo ligula, non placerat orci dapibus non. Ut commodo consectetur luctus.
<br>
<br>
Etiam suscipit at nibh sit amet luctus. Ut semper sed libero mollis maximus. Ut finibus efficitur nulla, sed ultricies augue sagittis accumsan. Donec molestie et risus at rutrum. Nulla id tempus est. Vivamus eleifend nulla a elit volutpat finibus. Aenean convallis aliquet mi quis suscipit. Suspendisse a feugiat nulla. Vestibulum suscipit volutpat gravida. Aliquam congue sit amet mi commodo fermentum. Cras rutrum id est at viverra. Nam elementum enim vel nunc sagittis laoreet. Aliquam eleifend metus et massa dictum rutrum. Donec quis finibus purus, non mollis erat. Sed tincidunt urna a laoreet fermentum.
<br>
<br>
Praesent vestibulum, nulla eget rutrum pretium, nibh augue imperdiet justo, id semper metus tellus at mi. In pharetra lacinia ligula, vitae feugiat nisi egestas a. Aliquam lorem dui, ullamcorper non vestibulum non, dictum quis neque. Morbi vitae urna purus. In ac erat ultrices, varius lacus vel, viverra nunc. Etiam vel felis ultrices, hendrerit ante quis, consequat mi. Nullam in tellus ligula. Nam ut sollicitudin risus. Pellentesque a commodo est, lacinia maximus turpis. Aenean congue in lorem quis congue. In hac habitasse platea dictumst. Aliquam quam turpis, dignissim ac quam vulputate, scelerisque luctus urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque a molestie dolor. Sed vel nulla metus.");

//GTU

define("_GTU","CGU");

//ACCESS DENY

define("_ACCESSDENY","Accès non autorisé !");

//FAQ

define("_MODIFY","Modifier");
define("_DELETE","Supprimer");
define("_ADDQUESTION","Ajouter une question/réponse :");
define("_QUESTION","Question");
define("_ANSWER","Réponse");
define("_LANGUAGE","Langage");

//user list

define("_NOMEMBER","Aucun membre");